# Read the documentation: https://github.com/FriendsOfSymfony/FOSElasticaBundle/blob/master/doc/setup.md
fos_elastica:
    clients:
        default: { url: '%env(ELASTICSEARCH_URL)%/' }
    indexes:
        resource:
            persistence:
                driver: orm
                model: App\Entity\Resource
                provider: ~
                finder: ~
            settings:
                analysis:
                    analyzer:
                        partial_analyzer:
                            tokenizer: 'partial'
                            filter : 'lowercase'
                    tokenizer:
                        partial:
                            type: 'edge_ngram'
                            min_gram: 3
                            max_gram: 15
            properties:
                slug:
                    type: 'keyword'
                name:
                    type: 'text'
                    analyzer : 'partial_analyzer'
                description:
                    type: 'text'
                    analyzer : 'partial_analyzer'
                level:
                    type: 'integer'
                imageUrl:
                    type: 'keyword'
                rarity:
                    type: 'nested'
                    include_in_root : true
                    properties:
                        name:
                            type: 'text'
                            analyzer : 'partial_analyzer'
                        icon:
                            type: 'keyword'
                        value:
                            type: 'integer'
                type:
                    type: 'nested'
                    include_in_root : true
                    properties:
                        name:
                            type: 'text'
                            analyzer : 'partial_analyzer'
                        icon:
                            type: 'keyword'
                        slug:
                            type: 'keyword'
        mob:
            persistence:
                driver: orm
                model: App\Entity\Mobs
                provider: ~
                finder: ~
            settings:
                analysis:
                    analyzer:
                        partial_analyzer:
                            tokenizer: 'partial'
                            filter : 'lowercase'
                    tokenizer:
                        partial:
                            type: 'edge_ngram'
                            min_gram: 3
                            max_gram: 15
            properties:
                slug:
                    type: 'keyword'
                name:
                    type: 'text'
                    analyzer : 'partial_analyzer'
                levelMin:
                    type: 'integer'
                levelMax:
                    type: 'integer'
                imageUrl:
                    type: 'keyword'
                family:
                    type: 'nested'
                    include_in_root : true
                    properties:
                        name:
                            type: 'text'
                            analyzer : 'partial_analyzer'
                        slug:
                            type: 'keyword'
        stuff:
            persistence:
                driver: orm
                model: App\Entity\Stuff
                provider: ~
                finder: ~
            settings:
                analysis:
                    analyzer:
                        partial_analyzer:
                            tokenizer: 'partial'
                            filter : 'lowercase'
                    tokenizer:
                        partial:
                            type: 'edge_ngram'
                            min_gram: 3
                            max_gram: 15
            properties:
                slug:
                    type: 'keyword'
                name:
                    type: 'text'
                    analyzer : 'partial_analyzer'
                description:
                    type: 'text'
                    analyzer : 'partial_analyzer'
                level:
                    type: 'integer'
                imageUrl:
                    type: 'keyword'
                rarity:
                    type: 'nested'
                    include_in_root : true
                    properties:
                        name:
                            type: 'text'
                            analyzer : 'partial_analyzer'
                        icon:
                            type: 'keyword'
                        value:
                            type: 'integer'
                type:
                    type: 'nested'
                    include_in_root : true
                    properties:
                        name:
                            type: 'text'
                            analyzer : 'partial_analyzer'
                        icon:
                            type: 'keyword'
                        slug:
                            type: 'keyword'
