name: deploiement auto
on: 
  push:
    branches:
    - main
jobs:
  deploy:
    name: Deploiement
    runs-on: ubuntu-latest
    steps:
    - name: executing remote ssh commands using password
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USERNAME }}
        key: ${{ secrets.SSH_KEY }}
        script: cd /home/debian/Waklab-api/.docker && sudo docker compose run php "./update.sh"